const data = {
  products: [
    {
      _id: '1',
      name: 'Herald Red',
      slug: 'herald-t-shirt-red',
      category: 'T-Shirts',
      image: '/images/herald-red.png',
      price: 29,
      quantityInStock: 50,
      rating: 5.0,
      reviews: 25,
      description:
        'The Herald T-Shirt is one of our first classic and legendary designs!',
    },
    {
      _id: '2',
      name: 'Bold Black',
      slug: 'bold-t-shirt-black',
      category: 'T-Shirts',
      image: '/images/bold-black&white.png',
      price: 29,
      quantityInStock: 50,
      rating: 5.0,
      reviews: 25,
      description:
        'The Bold T-Shirt is another classic design with a bold look!',
    },
    {
      _id: '3',
      name: 'Flywheel White',
      slug: 'flywheel-t-shirt-white',
      category: 'T-Shirts',
      image: '/images/flywheel-white&black.png',
      price: 29,
      quantityInStock: 50,
      rating: 5.0,
      reviews: 25,
      description:
        'The Flywheel T-Shirt is a fun design with a unique pattern!',
    },
    {
      _id: '4',
      name: 'Scepter Red',
      slug: 'scepter-t-shirt-red',
      category: 'T-Shirts',
      image: '/images/scepter-red&white.png',
      price: 29,
      quantityInStock: 50,
      rating: 5.0,
      reviews: 25,
      description:
        'The Scepter T-Shirt is a great t-shirt to impress the fans!',
    },
    {
      _id: '5',
      name: 'Splash Black',
      slug: 'splash-t-shirt-black',
      category: 'T-Shirts',
      image: '/images/splash-black&red.png',
      price: 29,
      quantityInStock: 50,
      rating: 5.0,
      reviews: 25,
      description: 'The Splash T-Shirt is a splash of SHT on a t-shirt!',
    },
    {
      _id: '6',
      name: 'Shield White',
      slug: 'shield-t-shirt-white',
      category: 'T-Shirts',
      image: '/images/shield-white.png',
      price: 29,
      quantityInStock: 50,
      rating: 5.0,
      reviews: 25,
      description: 'The Shield T-Shirt is a strong shield of SHT!',
    },
    {
      _id: '7',
      name: 'Bold Red',
      slug: 'bold-t-shirt-red',
      category: 'T-Shirts',
      image: '/images/bold-red&black.png',
      price: 29,
      quantityInStock: 50,
      rating: 5.0,
      reviews: 25,
      description:
        'The Bold T-Shirt is another classic design with a bold look!',
    },
    {
      _id: '8',
      name: 'Herald Black',
      slug: 'herald-t-shirt-black',
      category: 'T-Shirts',
      image: '/images/herald-black.png',
      price: 29,
      quantityInStock: 50,
      rating: 5.0,
      reviews: 25,
      description:
        'The Herald T-Shirt is one of our first classic and legendary designs!',
    },
    {
      _id: '9',
      name: 'Explosion White',
      slug: 'explosion-t-shirt-white',
      category: 'T-Shirts',
      image: '/images/explosion-white&red.png',
      price: 29,
      quantityInStock: 50,
      rating: 5.0,
      reviews: 25,
      description:
        'The Explosion T-Shirt is a great way to wear an explosion of SHT!',
    },
    {
      _id: '10',
      name: 'Flywheel Red',
      slug: 'flywheel-t-shirt-red',
      category: 'T-Shirts',
      image: '/images/flywheel-red&white.png',
      price: 29,
      quantityInStock: 50,
      rating: 5.0,
      reviews: 25,
      description:
        'The Flywheel T-Shirt is a fun design with a unique pattern!',
    },
    {
      _id: '11',
      name: 'Herald Rays Black',
      slug: 'herald-rays-t-shirt-black',
      category: 'T-Shirts',
      image: '/images/herald-rays-black.png',
      price: 29,
      quantityInStock: 50,
      rating: 5.0,
      reviews: 25,
      description:
        'The Herald Rays T-Shirt is the second version of one of our popular classics!',
    },
    {
      _id: '12',
      name: 'Bold White',
      slug: 'bold-t-shirt-white',
      category: 'T-Shirts',
      image: '/images/bold-white&black.png',
      price: 29,
      quantityInStock: 50,
      rating: 5.0,
      reviews: 25,
      description:
        'The Bold T-Shirt is another classic design with a bold look!',
    },
    {
      _id: '13',
      name: 'Spot Red',
      slug: 'spot-t-shirt-red',
      category: 'T-Shirts',
      image: '/images/spot-red&black.png',
      price: 29,
      quantityInStock: 50,
      rating: 5.0,
      reviews: 25,
      description: 'The Spot T-Shirt has left a great spot of SHT!',
    },
    {
      _id: '14',
      name: 'Sketch Black',
      slug: 'sketch-t-shirt-black',
      category: 'T-Shirts',
      image: '/images/sketch-black&white.png',
      price: 29,
      quantityInStock: 50,
      rating: 5.0,
      reviews: 25,
      description: 'The Sketch T-Shirt is a sketch of SHT greatness!',
    },
    {
      _id: '15',
      name: 'Stamp White',
      slug: 'stamp-t-shirt-white',
      category: 'T-Shirts',
      image: '/images/stamp-white&black.png',
      price: 29,
      quantityInStock: 50,
      rating: 5.0,
      reviews: 25,
      description:
        'The Stamp T-Shirt is a great classic with the SHT stamp of approval!',
    },
  ],
};

export default data;
